---
title: "Milestone 4"
author: "Ali Crump"
date: "2/28/2020"
output: pdf_document
bibliography: bibliography.bib
link_citations: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Loaded necessary libraries and created a bibliography file.

library(tidyverse)
library(knitr)
library(gt)
library(stargazer)

write_bib(c("knitr","stringr"), "bibliography.bib")

```

More information on this project can be found on my Github repository.^[[Github repository](https://github.com/alicrump/Fentanyl_Replication_Project)]

```{r make fake data}
# Here I'm just making fake data to put into my table.

delta <- round(rnorm(20,0,5), digits = 2)
age <- round(rnorm(20,40,20))
weight <- round(rnorm(20,130,20))

fake <- tibble(age,weight, delta)

```
```{r}
# Making the gt table of my fake data

table <- 
  fake %>% 
  slice(1:10) %>% 
  gt() %>% 
  tab_header(title = "Fake Table", 
             subtitle = "Effect of Some Treatment by Age") %>% 
  cols_label(age = "Age",
             delta = "Delta")

table
```

```{r}
# Making a model for my fake data

m2 <- lm(delta~age + weight, data = fake)
```

```{r regression table, results="asis",warning=FALSE}
# Set warning = FALSE because couldn't find an answer online to my error. Error
# was "length of NULL channot be changed" and can't seem to fix it. My table 
# shows up fine when I knit.

stargazer(m2, type = 'latex')

```

# References
@Replication, 
@Paper, 
@knitr2015